server:
  port: ${PORT:8080}
spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    driver: org.postgres.Driver
  liquibase:
    change-log: liquibase.yml
app:
  greetings-url: ${GREETINGS_URL:http://localhost:8080/}
